
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CURRENCY FLOAT SEPARATOR\n    expression : FLOAT CURRENCY SEPARATOR CURRENCY\n    '
    
_lr_action_items = {'FLOAT':([0,],[2,]),'$end':([1,5,],[0,-1,]),'CURRENCY':([2,4,],[3,5,]),'SEPARATOR':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> FLOAT CURRENCY SEPARATOR CURRENCY','expression',4,'p_expression','converter.py',32),
]
